### ISSUE TITLE
nil deference when triggered by Spot Termination Event

### ISSUE THREAD

**Issue by cfarrend** [LeanerCloud/AutoSpotting#358] opened 2019-08-13 06:12 UTC
## Issue type ##

- Bug Report

## Build number #

master branch

## Configuration ##

Deployed as a Stack Set, with a CloudWatch Rule triggering the function

## Summary ##

Can't confirm completely, but I believe the `logger` which is created from `main.go` 's `setupLogging` function does not get created, and therefore creating a nil pointer deference

It seems that `run()` is needed for it to be created, but it is never ran because the checks in `handler` direct straight to `NewSpotTermination`

To make it worse, it doesn't seem to happen every time and usually works when Lambda retries the function. So again not 100% sure if it's the actual issue

https://docs.aws.amazon.com/lambda/latest/dg/go-programming-model-errors.html

## Steps to reproduce ##

I had issues waiting for the CloudWatch Rule, so I set up an SNS topic to post to the Lambda with the example input
```
{
  "version": "0",
  "id": "84c3634d-2246-e3af-2e09-7a92cad1c032",
  "detail-type": "EC2 Spot Instance Interruption Warning",
  "source": "aws.ec2",
  "account": "xxx",
  "time": "2019-07-31T04:43:11Z",
  "region": "ap-southeast-2",
  "resources": ["arn:aws:ec2:ap-southeast-2b:instance/<instance>"],
  "detail": {
    "instance-id": "<instance>",
    "instance-action": "terminate"
  }
}

```

## Expected results ##

Function to continue running normally

## Actual results ##

nil pointer deference

```
runtime error: invalid memory address or nil pointer dereference: errorString
[
{
    "path": "github.com/aws/aws-lambda-go@v1.11.1/lambda/function.go",
    "line": 31,
    "label": "(*Function).Invoke.func1"
}
,
{
    "path": "runtime/panic.go",
    "line": 522,
    "label": "gopanic"
}
,
{
    "path": "runtime/panic.go",
    "line": 82,
    "label": "panicmem"
}
,
{
    "path": "runtime/signal_unix.go",
    "line": 390,
    "label": "sigpanic"
}
,
{
    "path": "log/log.go",
    "line": 153,
    "label": "(*Logger).Output"
}
,
{
    "path": "log/log.go",
    "line": 188,
    "label": "(*Logger).Println"
}
,
{
    "path": "github.com/AutoSpotting/AutoSpotting/core/spot_termination.go",
    "line": 38,
    "label": "NewSpotTermination"
}
,
{
    "path": "AutoSpotting/autospotting.go",
    "line": 137,
    "label": "Handler"
}
,
{
    "path": "reflect/value.go",
    "line": 447,
    "label": "Value.call"
}
,
{
    "path": "reflect/value.go",
    "line": 308,
    "label": "Value.Call"
}
,
{
    "path": "github.com/aws/aws-lambda-go@v1.11.1/lambda/handler.go",
    "line": 121,
    "label": "NewHandler.func1"
}
,
{
    "path": "github.com/aws/aws-lambda-go@v1.11.1/lambda/handler.go",
    "line": 24,
    "label": "lambdaHandler.Invoke"
}
,
{
    "path": "github.com/aws/aws-lambda-go@v1.11.1/lambda/function.go",
    "line": 63,
    "label": "(*Function).Invoke"
}
,
{
    "path": "reflect/value.go",
    "line": 447,
    "label": "Value.call"
}
,
{
    "path": "reflect/value.go",
    "line": 308,
    "label": "Value.Call"
}
,
{
    "path": "net/rpc/server.go",
    "line": 384,
    "label": "(*service).call"
}
,
{
    "path": "runtime/asm_amd64.s",
    "line": 1337,
    "label": "goexit"
}
]
```

**Comment by cristim** [comment] 2019-08-13 12:22
Thanks for reporting this issue.

I'm in the middle of a large refactoring which may have already addressed this, but I'll double check it soon.

Can you also reproduce it with the code from the feat/event-based-instance-replacement branch that I'm working on for #354?

You can install the latest build from this branch using the CloudFormation template custom/template.yaml from my S3 bucket.

**Comment by cfarrend** [comment] 2019-08-14 01:46
Hey @cristim I've been trying out the code from feat/event-based-instance-replacement and looks like this is not an issue. I've sent a bunch of termination events to the function and seems to be picked up correctly

**Comment by cfarrend** [comment] 2019-08-14 01:49
As an aside, perhaps we could catch the error if an instance no longer exists?

```
2019/08/14 01:47:28 Triggered by EC2 Spot Instance Interruption Warning
2019/08/14 01:47:28 spot_termination.go:38: Connection to region ap-southeast-2
runtime error: index out of range: errorString [{"path":"github.com/aws/aws-lambda-go@v1.11.1/lambda/function.go","line":31,"label":"(*Function).Invoke.func1"},{"path":"runtime/panic.go","line":522,"label":"gopanic"},{"path":"runtime/panic.go","line":44,"label":"panicindex"},{"path":"github.com/AutoSpotting/AutoSpotting/core/spot_termination.go","line":124,"label":"(*SpotTermination).getAsgName"},
runtime error: index out of range: errorString
[
{
    "path": "github.com/aws/aws-lambda-go@v1.11.1/lambda/function.go",
    "line": 31,
    "label": "(*Function).Invoke.func1"
}
,
{
    "path": "runtime/panic.go",
    "line": 522,
    "label": "gopanic"
}
,
{
    "path": "runtime/panic.go",
    "line": 44,
    "label": "panicindex"
}
,
{
    "path": "github.com/AutoSpotting/AutoSpotting/core/spot_termination.go",
    "line": 124,
    "label": "(*SpotTermination).getAsgName"
}
,
{
    "path": "github.com/AutoSpotting/AutoSpotting/core/spot_termination.go",
    "line": 137,
    "label": "(*SpotTermination).executeAction"
}
,
{
    "path": "github.com/AutoSpotting/AutoSpotting/core/main.go",
    "line": 213,
    "label": "(*AutoSpotting).EventHandler"
}
,
{
    "path": "AutoSpotting/autospotting.go",
    "line": 45,
    "label": "eventHandler"
}
,
{
    "path": "AutoSpotting/autospotting.go",
    "line": 78,
    "label": "Handler"
}
,
{
    "path": "reflect/value.go",
    "line": 447,
    "label": "Value.call"
}
,
{
    "path": "reflect/value.go",
    "line": 308,
    "label": "Value.Call"
}
,
{
    "path": "github.com/aws/aws-lambda-go@v1.11.1/lambda/handler.go",
    "line": 121,
    "label": "NewHandler.func1"
}
,
{
    "path": "github.com/aws/aws-lambda-go@v1.11.1/lambda/handler.go",
    "line": 24,
    "label": "lambdaHandler.Invoke"
}
,
{
    "path": "github.com/aws/aws-lambda-go@v1.11.1/lambda/function.go",
    "line": 63,
    "label": "(*Function).Invoke"
}
,
{
    "path": "reflect/value.go",
    "line": 447,
    "label": "Value.call"
}
,
{
    "path": "reflect/value.go",
    "line": 308,
    "label": "Value.Call"
}
,
{
    "path": "net/rpc/server.go",
    "line": 384,
    "label": "(*service).call"
}
,
{
    "path": "runtime/asm_amd64.s",
    "line": 1337,
    "label": "goexit"
}
]
```

**Comment by cfarrend** [comment] 2019-08-14 08:41
@cristim I don't do golang too much but maybe something like this
`spot_termination.go`

```
func (s *SpotTermination) getAsgName(instanceID *string) (string, error) {
	asParams := autoscaling.DescribeAutoScalingInstancesInput{
		InstanceIds: []*string{instanceID},
	}

	result, err := s.asSvc.DescribeAutoScalingInstances(&asParams)

	var asgName = ""

	if len(result.AutoScalingInstances) == 0 {
		err = errors.New("No autoscaling group could be found. Does the instance exist?")
	}

	if err == nil {
		asgName = *result.AutoScalingInstances[0].AutoScalingGroupName
	}

	return asgName, err
}
```

**Comment by cristim** [comment] 2019-08-14 09:54
Thanks, I'll have a look at this soon.

Great to hear that it's working well with the current state of that branch

**Comment by cristim** [comment] 2019-09-18 14:44
Note to self: re-check this after the branch is merged.

**Comment by gabegorelick** [comment] 2020-01-30 02:36
> To make it worse, it doesn't seem to happen every time and usually works when Lambda retries the function.

It may work because the global variable was initialized in an earlier invocation of the Lambda. If the Lambda isn't "thawed" then I think it should fail 100% of the time.

> Note to self: re-check this after the branch is merged.

I was going to try and land the conf and setup portion of that branch if I have time. But that still may take some time. So I think I may try to fix this bug separately.

**Comment by cristim** [comment] 2023-03-06 16:34
I think this is no longer relevant, so I'm closing it

@cfarrend, @gabegorelick: let me know if you can still reproduce this with the latest version and happy to reopen it.

**Closed by cristim** 2023-03-06 16:34 UTC
Labels: Type: Bug, Status: Need testing, Type: Good first issue, Importance: Minor, Difficulty: Easy, Status: outdated (to re-check)
